replicaCount: 1

image:
  repository: rsh4297/cloud-pipeline-go
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
